maniyaom/Movie-Ticket-Booking

src/components/Navbar.js
src/context/firebase.js

Fix for the issue #8
**Description:**
This PR addresses the issue of sensitive information being logged in the browser console. It ensures that all critical data is removed, enhancing user privacy and security.
**Changes Made:**
- Cleared unnecessary logs from the console.
- Removed sensitive user information that was previously being logged during sign-in and other interactions.
**Related Issues:**
- Closes #8

Clear Console and Remove Critical Information

---

src/Pages/Home.css
src/Pages/utils.css
src/components/Navbar.css
src/components/Navbar.js

#9 I have added max width to textarea.

fix overflow of textarea 

---

src/Pages/AboutUs.js
src/Pages/ContactUs.js
src/components/Navbar.js

i have improved this dropdown menu so that it disabled onclicking any item present in it also desabled on onclicking rest of page.
I have add some functions and css.

dropdown menu improved

---

src/components/Footer.css

I have implemented responsive footer as assigned in the issue #22  for me for gssoc ext and hacktober fest.
Please find the below demo  of implementation
**Desktop:**
**Tablet:**
**Mobile:**

feat : Responsive footer for various screen sizes

---

src/Pages/AboutUs.css
src/Pages/AboutUs.js
src/Pages/ContactUs.js
src/Pages/Login.js
src/Pages/style.css

hi i made the adout us contact us and login page responsive this time with no conflicts 
please review and merge @maniyaom

#14 about us, contact us and login page responsive for small screens

---

CONTRIBUTION.md
CONTRIBUTIONG.md

#16 
Commited  request for urgent pls check ,edit and add some more contribution guidelines

Added Contribution.md

---

package-lock.json
package.json
src/App.js
src/Pages/Notifications.js
src/components/Navbar.js
src/index.js

Issue: https://github.com/maniyaom/Movie-Ticket-Booking/issues/39
The notification bell is added, after clicking on the notification bell it will redirect to /notification page
after clicking:

Notification button Added

---

src/Pages/BookTicket.js
src/Pages/MovieTicket.js
src/Pages/MyTickets.js
src/components/Navbar.css
src/components/Navbar.js
src/context/firebase.js
src/index.js

Hi @maniyaom 
**The project has been updated** 
Here, is the screenshot
Also to mention that **My Tickets** option in navbar will only showup once the user is logged in to the account

Added the feature of My Tickets

---

src/components/Navbar.css

Reference issue #67 
issue of visible subheading under navbar is fixed.

navbar fixed 

---

src/Pages/AddMovie.js

Changed the Movie Duration Format to (HH:MM:SS) and properly validated the input.

Fixed #78: Movie Duration Bug Fixed

---

src/Pages/Login.js
src/Pages/SignUp.js

fixes issue #77 
PR Summary:
Added Features:
Implemented email format validation during user login to ensure users provide valid email addresses.
Changes Made:
Updated the login form validation logic to include a regex-based check for valid email formats.
Enhanced error handling by providing specific feedback to users when the email format is incorrect or required fields are empty.
This update enhances the login process by preventing invalid email submissions, leading to a smoother user experience.

email format validation added

---

.github/workflow/greetings.yml

Have designed a workflow which will greet user on their email and in the issue raising chat for raising a issue or PR
Resolved issues
#111

Added automated greetings

---

package-lock.json
package.json
src/Pages/MovieTicket.js
src/Pages/Verify.css
src/Pages/Verify.js
src/components/Navbar.js
src/context/firebase.js
src/index.js

1. Replaced the Dummy QR and Generated a QR for the ticket.
2. After a single successful validation ticket will become invalid after that. but, if it is scanned for the second time the ticket will be invalid. 
3. The Verification is enabled only for Admins.

Fix #133 Added QR Generation and Verification for a Ticket

---

src/components/Search.js

Fixed Issue number #183 
Added debouncing effect of 1000ms for searching feature.

Added debouncing effect

---

src/policies/privacy-policy.js

**fix for the issue #58**
- Privacy policy page added with tailwind CSS migration.
Still working on terms and condition page, I'll update that soon.

privacy-policy.js added.

---

src/Pages/AddMovie.js
src/Pages/utils.css

Fixes: #228 
Implemented Required validation for listing movie and also added default timing values to movie timings.
@maniyaom Please check it out.

Fixes #228  Validation and Timings updated for listing a Movie 

---

package-lock.json
src/components/Navbar.css

fixes #281
- there was extra margin on top on navbar, which got fixed

extra margin fixed of issue #281

---

src/Pages/ForgotPassword.js
src/Pages/Login.js
src/Pages/SignUp.js
src/context/firebase.js
src/index.js

Implemented Forgot Password and Signup **issue no #318** 
1. Forgot Password 
2.  Signup
3. Remove some problems

Implemented Forgot Password and Signup 

---

src/components/GoogleTranslate.jsx
src/components/Navbar.js

Here's a sample pull request (PR) template for implementing multilingual support in a ticket booking application. You can modify it to fit your project's specific requirements and conventions.
---
This pull request implements multi-lingual support for the movie ticket booking application, allowing users to view the interface in multiple languages. The feature enhances user experience by catering to a diverse audience and ensuring accessibility for non-English speakers.
1. **Language Selection Feature:**
- Added a dropdown menu for users to select their preferred language.
- Languages supported: English, Hindi, Spanish, French and many more.
2. **Dynamic Text Rendering:**
- Modified components to render text dynamically based on the selected language. …

Multi-Lingual Support for Ticket Booking

---

package-lock.json
package.json
src/Pages/Feedback.js
src/components/Navbar.js
src/context/firebase.js
src/index.js

issue no. : #356 
I've resolve the issue of the previous PR of feedback section. #363

Resolved the issue of the previous PR of feedback section.

---

package-lock.json
package.json
src/Pages/Feedback.js
src/components/Navbar.js
src/context/firebase.js
src/index.js

I've changed the Feedback theme changed according to the websites theme
I've resolve the issue of the previous PR of feedback section.: #363

Feedback theme changed according to the websites theme

---

package-lock.json
package.json
src/Pages/AboutUs.css
src/Pages/AboutUs.js

I have updated the testimonial section into a horizontal slider carousel using react-bootstrap. Additionally, I made some CSS changes to enhance the testimonial section's appearance and ensure the functionality works properly across different screen sizes.
The carousel is fully responsive, adjusting seamlessly for both mobile and desktop views to provide a consistent and user-friendly experience.
To support this update, I installed the following library:   react-bootstrap bootstrap

 updated testimonial
